# Generated by Django 3.0.8 on 2020-08-26 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form2', '0036_auto_20200820_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form2',
            name='Sorumlusu',
            field=models.CharField(choices=[], max_length=25, verbose_name='Sorumlu Kişiyi Ata'),
        ),
    ]
